### ISSUE TITLE
Remove Mapping name as it is useless

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-dynamic-mapper#101]
Currently we generate random mapping names on import and creation of mapping. Actually they are useless and should be replaced by the mapping topic which is more meaningful and therefor readable by users.

**Comment by sagIoTPower** [comment]
What could be a useful algorithm/ approach to generate a name for the mapping?

The mapping name is the first property on the screen.
The subscriptionTopic can be lengthy including multiple levels: 
`company-iote97b489-75b2-4a6e-92a9-0f5f02960264/ Factory - Parma/Production line/Line 1 mixer/TURBOMIXX Mixer EDF/TURBOMIXX Pipeline WDF/#`
And it is second in order after the name. So to update the name after you added the subscriptionTopic will be confusing.

On easy solution could be to count the number of currently added mappings and raise this count, e.g. if you currently have 12 mappings and add a new mapping, this is named:

Mapping - 13

**Comment by sagIoTPower** [comment]
This proposal is included in: b6c1822e9b0182dc3e85f87a254282aa81ce11b6
