### ISSUE TITLE
External Id type is blank after disable/enable Map device identifier

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-dynamic-mapper#105]
If you enable Map device identifier once the External Id type field is prefilled with "c8y_Serial".
If you disable and enable it again the field is blank and let you proceed which leads to an error later on.

Expected Behavior: When Map device identifier is active  the External Id type field must be mandatory before you can proceed
Default value "c8y_Serial" should appear even after disable and enable again.

**Comment by sagIoTPower** [comment]
The implementation was changed in: 3e0f6ec94b9577053b1d67be2353eba473222572.
Could you pls. verify if this fixes the bug?
