### ISSUE TITLE
Improve First-usage of Dynamic Mapper

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-dynamic-mapper#171]
Currently the user is not very well guided within the UI.
Normally the Mapper Role must be assigned to a user and a connector must be configured as the first steps. Without reading the docs user tend to create mappings first without having any connectors configured.

As an improvement we can implement the following:
1. When no connector is configured we could raise an info/warning "No connector is configured. Please create a connector"
2. The Connector Tab is visible but read-only without the specific role.
2.1 Display a warning in the connector Tab when no connector is configured and role is not assigned to the user: "Role xyz is required to create/update connectors". If at least one connector is configured we should not display that warning
3. When activating a mapping and no connector is configured we should display an error and prevent activating mapping: "No connector configured. Please create a connector first before activating mappings".

**Comment by sagIoTPower** [comment]
This was included in 4ad353cc2cb1438c443455ca3c8523aef517cbec
