### ISSUE TITLE
User feedback about activated mappings

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-dynamic-mapper#178]
Currently if a mapping could not be activated for some connectors the user does not receive any feedback.

Suggested Improvement: When activating a mapping the message "Could not be activated for connector x". 

Reason for this could be because a connector is not supporting some specific mappings e.g. wildcard mappings.

Other Improvement: Check during mapping creation that this will not be working for connector x.

Concrete Example: MQTT Service + Mapping created for "events/#" etc. Mapping could be activated but no feedback given to the user afterwards.

**Comment by sagIoTPower** [comment]
The first improvements were in included in:
1. redesign snoop process part 1 9dee228b5511ddd8501457bd5575c19d6f0e334d
2. redesign snoop process part 2 f6ccfd3ccb1e8b15fbd8807b243fe2a7482f2073

**Comment by sagIoTPower** [comment]
This enhancement was included in 198a9c25f6a6cba5bfa9c54ccbe455f47672868a
