### ISSUE TITLE
Activate Mappings per Connector

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-dynamic-mapper#184]
Currently mappings are activated for all activated connectors.
There might be use cases where some mappings should be only activated for specific connectors. For example you define a mapping on a subscription topic which is used in both connectors but have different payloads.

Improvement: 
-In the first view of a mapping there should be a Connector picker which is defaulted to "All connectors"
-Here you can pick one or multiple connectors the mappings should be activated for.

We might need to change the data model of mappings so a List of connectorIdents is part of each persisted mapping.
On export/import this information should be ignored or we add an optional flag to default it to "all connectors" on export/import.

**Comment by sagIoTPower** [comment]
As part of the stepper you can now select/deselect connectors for the mapping.
The selection is the first step of the stepper.

In the data grid of all mappings a new column "effective connectors" is added.
This inform the user if the can receive payload and the substitutions are applied.
This happen if all of the following conditions are met:
1. mapping is active
2. an active connector is selected for the mapping
3. the selected connectors support wildcards, if the mapping uses wildcards

The feature is included in commit 4c09f9dc1faf962fafd5233c8b3c3cf86928d372
