### ISSUE TITLE
Write concept for multi tenancy

### ISSUE THREAD

**Issue by sagIoTPower** [SoftwareAG/cumulocity-dynamic-mapper#2]
Currently the generic mqtt agent only works for a single tenant.
What should happen if multiple tenants subscribe to the microservice?
If multiple tenants subscribe to the ms they all would create their own mappings.
All use one connection to the mqtt broker, so their topics couls possibly interfere and be defined twice, e.g.:
1. tenant 1 uses topic "myAlarms"
2. tenant 2 uses topic "myAlarms"

So topics need to be unique across different tenants. This seems to be a strong requirement and violates the isolations of tenant data.

**Comment by switschel** [comment]
For the beginning I would work with the following assumptions:
* Per Tenant you can have one MQTT Connection (stored in Tenant Options)
** This follows that the MQTT connection is not shared across Tenants but for each Tenant you have your own connection.
** Later one we can support multiple MQTT Connections per Tenants if desired but still isolated per tenant.
* Per Tenant you can have multiple Mappings (stored in the Tenant)

The topic interfere is typical MQTT issue. I would not implement anything for that. In some use cases topics should be shared across tenants in other use case you don't want that and use unique topic names for each tenant.

Example Use case: Having a device in Tenant A and Tenant B at the same time. In Tenant A just for basic monitoring, in Tenant B for deep analysis of data. Both might get alarms but only Tenant B is interested in getting details about the device.

**Comment by switschel** [comment]
Additional remarks:
- We make the c8yAgent instance able with the tenant as a required parameter and key.
- A c8yAgent can have one (or later multiple MQTT client).
- On each new tenant added @EventListerner we create a new instance of the c8yAgent for each tenant and instantiate the MQTTClients to the stored MQTT Broker.
- The mappings will be also loaded based on the tenant.

**Comment by switschel** [comment]
Resolved with 4.0.0 release
