### ISSUE TITLE
Cannot see substitution editor when adding inbound mapping

### ISSUE THREAD

**Issue by zhong-ys** [SoftwareAG/cumulocity-dynamic-mapper#218]
I'm using the latest version 4.4.0 on eu-latest and Thick Edge k8s 10.18. Got the same issue on both of them. 

When I tried to add an inbound mapping, in step 3 Select templates, the editor for substitution (add substitution tab, update substitution tab and substitution list) didn't show up. 
<img width="1512" alt="3selectempates" src="https://github.com/user-attachments/assets/8b2f72d9-4e8b-48e1-835b-7fd069cd8ba6">

In step 2 Properties mapping page, I could not scroll down. 

Tried to install 4.4.0 version Dynamic mapper Microservice on Thick Edge VM, got 'push failed on image' again. It seems that the fix for docker version issue hasn't been updated on Thick Edge VM.

**Comment by switschel** [comment]
This is on purpose. We separated the template and substitution page. Just click Next and you should see your substitutions.

**Comment by zhong-ys** [comment]
Thank you for your help! I will close this ticket.
