### ISSUE TITLE
Adding substitutions in Expert mode does not work

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-dynamic-mapper#264]
When clicking on "Add substitution" here:
![image](https://github.com/user-attachments/assets/42d42d04-3008-474e-8421-f68cfbd4f715)

A popup opens:
![image](https://github.com/user-attachments/assets/8397de7b-7e79-4d55-af05-74e2daafd68e)

When clicking save here, nothing happens. Specifically the list of substitutions is not updated. One has to disable "Expert mode" and then click on "Add substitution" for the substitution to be added.

**Comment by sagIoTPower** [comment]
This is a duplicate of #258 and can be tested if it works in [pre release](https://github.com/SoftwareAG/cumulocity-dynamic-mapper/releases/tag/untagged-0b422f83163377fcbd99)
for 4.5.2.

**Comment by haraldmeyer** [comment]
Duplicate.
