### ISSUE TITLE
Group nav bar entries when installed as extension into existing application

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-dynamic-mapper#267]
Currently, it looks like this is only the case in Administration. In Device Management it looks like this:

![image](https://github.com/user-attachments/assets/b97180a1-10eb-4cfe-af6e-8537b448e47f)

**Comment by switschel** [comment]
@sagIoTPower We should remove the "administration" filter and always have 1 top level menu when using as a plugin in all apps.

**Comment by sagIoTPower** [comment]
This should have been like you proposed. 
This was a bug. Fixed in d62e8071c9cf633baeb7ae857838027baa9ce4d7
![Screenshot 2024-10-01 at 08 25 30](https://github.com/user-attachments/assets/10c5cbb6-84f2-4990-bb81-d981ba61cc4a)

**Comment by haraldmeyer** [comment]
Thank you!
