### ISSUE TITLE
Improve visual indication when Broker connection fails

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-dynamic-mapper#268]
Make the connection icon red instead of grey:

![image](https://github.com/user-attachments/assets/c5cb234e-d7a9-44b5-801d-4ce7ecc9055f)

**Comment by sagIoTPower** [comment]
![Screenshot 2024-10-01 at 08 07 28](https://github.com/user-attachments/assets/c4c69280-4205-4d05-b35f-6604c18b780c)
I propose this layout. Easier to grasp?

**Comment by sagIoTPower** [comment]
This is fixed here: [a57d69594a44ff7c40a4294dcb8ad20861165e42](https://github.com/SoftwareAG/cumulocity-dynamic-mapper/commit/a57d69594a44ff7c40a4294dcb8ad20861165e42)

**Comment by haraldmeyer** [comment]
yes.
