### ISSUE TITLE
Replace paho mqtt client

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-dynamic-mapper#88]
Replace paho mqtt client with a more recent maintained and stable MQTT client e.g.
https://github.com/hivemq/hivemq-mqtt-client

**Comment by switschel** [comment]
Added hivemq mqtt client to develop branch 

https://github.com/SoftwareAG/cumulocity-dynamic-mapper/commit/6a61dcb25f38b5b5a4fdcaf8e2b09afd30591dbc

**Comment by sagIoTPower** [comment]
This was released as part of release [v4.2.0](https://github.com/SoftwareAG/cumulocity-dynamic-mapper/releases/tag/v4.2.0)
